### ISSUE TITLE
"path" example doesn't work

### ISSUE THREAD

**Issue by wimglenn** [cjw296/carthorse#2]
```
$ carthorse
Traceback (most recent call last):
  File "/tmp/p/.venv/bin/carthorse", line 8, in <module>
    sys.exit(main())
  File "/tmp/p/.venv/lib/python3.10/site-packages/carthorse/cli.py", line 19, in main
    version = config.run(plugins['version_from'], config['version-from'])
  File "/tmp/p/.venv/lib/python3.10/site-packages/carthorse/config.py", line 44, in run
    return plugins[config['name']](*config['args'], **kw)
KeyError: 'path'
```

Instead of 

    version-from = { name="path", path="setup.py", pattern="version='(?P<version>[^']+)" }

I needed to use 

    version-from = { file = { path="setup.py", pattern="version='(?P<version>[^']+)" } }

**Comment by cjw296** [comment]
Fixed in 4b4410dff118f0ff83c611c0a57f1d4b1cc53137, tests added in ad3794b4e97c9a737bb3bfc5ec52b6268e00c419 :-)
